<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.customer" Member="customer">
    <Type Name="customer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="surname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="customer_main" Member="main" ThisKey="Id" OtherKey="id_customer" Type="main" />
    </Type>
  </Table>
  <Table Name="dbo.main" Member="main">
    <Type Name="main">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_pizza" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_customer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="customer_main" Member="customer" ThisKey="id_customer" OtherKey="Id" Type="customer" IsForeignKey="true" />
      <Association Name="menu_main" Member="menu" ThisKey="id_pizza" OtherKey="Id" Type="menu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.menu" Member="menu">
    <Type Name="menu">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name_pizza" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cost" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="info" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="menu_main" Member="main" ThisKey="Id" OtherKey="id_pizza" Type="main" />
    </Type>
  </Table>
</Database>